### ISSUE TITLE
"Meetups" should point to official meetup page instead of terribly old meetup notes

### ISSUE THREAD

**Issue by emilsoman** [bangaloreruby/bangaloreruby.github.com#21]
Let's point the "Meetups" link at the official meetup.com page instead of the past meetup notes since these notes have become too old and nobody's adding notes anymore.

**Comment by swanandp** [comment]
:+1:

**Comment by swanandp** [comment]
This is the official meetup.com page: http://meetup.com/Bangalore-Ruby-Users-Group/
