### ISSUE TITLE
bangaloreruby.org fails to load assets

### ISSUE THREAD

**Issue by Roshanjossey** [bangaloreruby/bangaloreruby.github.com#27]
This is what I got in console when I go to http://bangaloreruby.org

```
http://bangaloreruby.org/assets/themes//css/style.css Failed to load resource: the server responded with a status of 404 (Not Found)
modernizr.min.js:4 'webkitIndexedDB' is deprecated. Please use 'indexedDB' instead.
r.indexedDB @ modernizr.min.js:4
(index):152 The deviceorientation event is deprecated on insecure origins, and support will be removed in the future. You should consider switching your application to a secure origin, such as HTTPS. See https://goo.gl/rStTGz for more details.
(anonymous) @ (index):152
http://bangaloreruby.org/assets/themes//images/ruby_normal.png Failed to load resource: the server responded with a status of 404 (Not Found)
http://img1.meetupstatic.com/9260736631256287675/img/star_450.png Failed to load resource: the server responded with a status of 404 (Not Found)
http://img1.meetupstatic.com/84869143793177372874/img/birddog/everywhere_widget.png Failed to load resource: the server responded with a status of 404 (Not Found)
http://bangaloreruby.org/favicon.ico Failed to load resource: the server responded with a status of 404 (Not Found)
http://bangaloreruby.org/assets/themes//css/style.css Failed to load resource: the server responded with a status of 404 (Not Found)
```

**Comment by hemanth** [comment]
I updated the `modernizr` version, I am not able to recall if auto deploy was set up.

**Comment by Roshanjossey** [comment]
@hemanth: I tried running this in local and it works perfectly.

I also looked through commit history to find something about deployment. Couldn't find anything.

Do you have any clues?

**Comment by swanandp** [comment]
The website is broken, as of now. @hemanth would you be able to look into this?

**Comment by hemanth** [comment]
> I tried running this in local and it works perfectly.

That suggests the code base is fine. 

I don't see a `gh-pages` branch, I am not able to recall when was the last deployment or how we did it.

**Comment by swanandp** [comment]
@arunagw Any idea?

**Comment by arunagw** [comment]
Seems like recent version of Jekyll is the problem.

**Comment by hemanth** [comment]
```rb
> rake -T
rake page           # Create a new page.
rake post           # Begin a new post in ./_posts
rake preview        # Launch preview environment
rake theme:install  # Install theme
rake theme:package  # Package theme
rake theme:switch   # Switch between Jekyll-bootstrap themes.
```

No deploy as such.

**Comment by hemanth** [comment]
`gem 'jekyll', '~> 2.0.0' # This change was made via Snyk to fix a vulnerability` hmm...

**Comment by arunagw** [comment]
repo is deployed via GitHub pages so everything in master gets deployed.

**Comment by arunagw** [comment]
@hemanth you should be able to see `settings` page for this repo now.

**Comment by Roshanjossey** [comment]
@hemanth, @arunagw, I found this while googling about this.
https://github.com/plusjade/jekyll-bootstrap/issues/295

In that thread, they suggest 
>In JB/Setup the script uses {{ page.theme.name }}, but it seems that in Jekyll 3, it has to be {{ layout.theme.name }}.
Would it solve our problem? (I'm unsure about this because we're using jekyll 2.0.3

**Comment by Roshanjossey** [comment]
I tried this somewhere else and worked correctly.

I'll submit a PR now

**Comment by hemanth** [comment]
:+1:
